import type { ExerciseDef } from './types'

export const EXERCISES: ExerciseDef[] = [
  {
    id: 'bench_press',
    name: 'Barbell Bench Press',
    movement: 'horizontal_push',
    type: 'compound',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    movement: 'horizontal_push',
    type: 'compound',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    movement: 'horizontal_push',
    type: 'compound',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts', 'abs'],
  },
  {
    id: 'ohp',
    name: 'Overhead Press',
    movement: 'vertical_push',
    type: 'compound',
    primary: ['front_delts', 'triceps'],
    secondary: ['side_delts', 'upper_back'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    movement: 'vertical_push',
    type: 'isolation',
    primary: ['side_delts'],
  },
  {
    id: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    movement: 'horizontal_push',
    type: 'isolation',
    primary: ['triceps'],
  },
  {
    id: 'dips',
    name: 'Dips (Assisted if needed)',
    movement: 'vertical_push',
    type: 'compound',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
  },

  {
    id: 'pull_up',
    name: 'Pull-Up (Assisted if needed)',
    movement: 'vertical_pull',
    type: 'compound',
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    movement: 'vertical_pull',
    type: 'compound',
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    movement: 'horizontal_pull',
    type: 'compound',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'lower_back'],
  },
  {
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    movement: 'horizontal_pull',
    type: 'compound',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    movement: 'horizontal_pull',
    type: 'compound',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    movement: 'horizontal_pull',
    type: 'isolation',
    primary: ['rear_delts', 'upper_back'],
  },
  {
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    movement: 'horizontal_pull',
    type: 'isolation',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
  },
  {
    id: 'biceps_curl',
    name: 'Dumbbell Curl',
    movement: 'horizontal_pull',
    type: 'isolation',
    primary: ['biceps'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    movement: 'horizontal_pull',
    type: 'isolation',
    primary: ['biceps'],
    secondary: ['upper_back'],
  },

  {
    id: 'back_squat',
    name: 'Back Squat',
    movement: 'squat',
    type: 'compound',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'lower_back', 'abs'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    movement: 'squat',
    type: 'compound',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift (RDL)',
    movement: 'hinge',
    type: 'compound',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back'],
  },
  {
    id: 'deadlift',
    name: 'Deadlift (Conventional)',
    movement: 'hinge',
    type: 'compound',
    primary: ['glutes', 'hamstrings', 'lower_back'],
    secondary: ['upper_back', 'abs'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    movement: 'hinge',
    type: 'compound',
    primary: ['glutes'],
    secondary: ['hamstrings', 'abs'],
  },
  {
    id: 'split_squat',
    name: 'Bulgarian Split Squat',
    movement: 'squat',
    type: 'compound',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'abs'],
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    movement: 'hinge',
    type: 'isolation',
    primary: ['hamstrings'],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    movement: 'squat',
    type: 'isolation',
    primary: ['quads'],
  },
  {
    id: 'calf_raise',
    name: 'Standing Calf Raise',
    movement: 'carry',
    type: 'isolation',
    primary: ['calves'],
  },

  {
    id: 'plank',
    name: 'Plank',
    movement: 'core',
    type: 'isolation',
    primary: ['abs'],
    secondary: ['lower_back'],
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    movement: 'core',
    type: 'isolation',
    primary: ['abs'],
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    movement: 'core',
    type: 'isolation',
    primary: ['abs'],
  },
]

export function getExerciseById(exerciseId: string) {
  return EXERCISES.find((e) => e.id === exerciseId)
}

